# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="user.proto",
    package="user",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\nuser.proto\x12\x04user">\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t"\x1d\n\x0fUserInfoRequest\x12\n\n\x02id\x18\x01 \x01(\t",\n\x10UserInfoResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User2Q\n\x0fUserInfoService\x12>\n\x0bGetUserInfo\x12\x15.user.UserInfoRequest\x1a\x16.user.UserInfoResponse"\x00\x62\x06proto3',
)


_USER = _descriptor.Descriptor(
    name="User",
    full_name="user.User",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="user.User.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="login",
            full_name="user.User.login",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="email",
            full_name="user.User.email",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="role",
            full_name="user.User.role",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=20,
    serialized_end=82,
)


_USERINFOREQUEST = _descriptor.Descriptor(
    name="UserInfoRequest",
    full_name="user.UserInfoRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="user.UserInfoRequest.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=84,
    serialized_end=113,
)


_USERINFORESPONSE = _descriptor.Descriptor(
    name="UserInfoResponse",
    full_name="user.UserInfoResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="user",
            full_name="user.UserInfoResponse.user",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=115,
    serialized_end=159,
)

_USERINFORESPONSE.fields_by_name["user"].message_type = _USER
DESCRIPTOR.message_types_by_name["User"] = _USER
DESCRIPTOR.message_types_by_name["UserInfoRequest"] = _USERINFOREQUEST
DESCRIPTOR.message_types_by_name["UserInfoResponse"] = _USERINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType(
    "User",
    (_message.Message,),
    {
        "DESCRIPTOR": _USER,
        "__module__": "user_pb2"
        # @@protoc_insertion_point(class_scope:user.User)
    },
)
_sym_db.RegisterMessage(User)

UserInfoRequest = _reflection.GeneratedProtocolMessageType(
    "UserInfoRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERINFOREQUEST,
        "__module__": "user_pb2"
        # @@protoc_insertion_point(class_scope:user.UserInfoRequest)
    },
)
_sym_db.RegisterMessage(UserInfoRequest)

UserInfoResponse = _reflection.GeneratedProtocolMessageType(
    "UserInfoResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERINFORESPONSE,
        "__module__": "user_pb2"
        # @@protoc_insertion_point(class_scope:user.UserInfoResponse)
    },
)
_sym_db.RegisterMessage(UserInfoResponse)


_USERINFOSERVICE = _descriptor.ServiceDescriptor(
    name="UserInfoService",
    full_name="user.UserInfoService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=161,
    serialized_end=242,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetUserInfo",
            full_name="user.UserInfoService.GetUserInfo",
            index=0,
            containing_service=None,
            input_type=_USERINFOREQUEST,
            output_type=_USERINFORESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_USERINFOSERVICE)

DESCRIPTOR.services_by_name["UserInfoService"] = _USERINFOSERVICE

# @@protoc_insertion_point(module_scope)
