# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import user_pb2 as user__pb2


class UserInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserInfo = channel.unary_unary(
            "/user.UserInfoService/GetUserInfo",
            request_serializer=user__pb2.UserInfoRequest.SerializeToString,
            response_deserializer=user__pb2.UserInfoResponse.FromString,
        )


class UserInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetUserInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserInfo,
            request_deserializer=user__pb2.UserInfoRequest.FromString,
            response_serializer=user__pb2.UserInfoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "user.UserInfoService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class UserInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user.UserInfoService/GetUserInfo",
            user__pb2.UserInfoRequest.SerializeToString,
            user__pb2.UserInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
