version: '3'

services:
  web:
    build: .
    image: movies-billing
    container_name: movies-billing
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres:14.1
    container_name: movies-billing-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"