# Generated by Django 3.2.11 on 2022-01-31 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djstripe", "0010_alter_customer_balance"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="BillingCustomer",
        ),
    ]
